[package]
name = "fulcrim"
version = "0.2.0"
authors = ["Philip Ormand <pro@ruda.com>"]
edition = "2021"

[package.metadata.cargo-all-features]
skip_optional_dependencies = true

[dependencies]
cfg-if = "1.0"

macro-attr-2018 = { optional = true, version = "3.0" }
newtype-derive-2018 = { optional = true, version = "0.2.1" }
paste = { optional = true, version = "1.0" }
serde = { optional = true, version = "1.0", features = ["derive"] }
ulid = { optional = true, version = "1.0" }
web-time = { optional = true, version = "0.2.3" }

[features]
ulid-id = [
    "dep:macro-attr-2018",
    "dep:newtype-derive-2018",
    "dep:paste",
    "dep:ulid",
]
serde = ["dep:serde", "ulid/serde"]

[dev-dependencies]
impls = "1.0"
serde_test = "1.0"
